# Generated by Django 2.1.7 on 2019-03-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('shortcut', models.CharField(max_length=350, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=350)),
                ('type', models.CharField(default=1, max_length=5)),
                ('high', models.IntegerField(blank=True, default=0)),
                ('mid', models.IntegerField(blank=True, default=0)),
                ('low', models.IntegerField(blank=True, default=0)),
                ('info', models.IntegerField(blank=True, default=0)),
                ('risk', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': '"assets"',
            },
        ),
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('reporthash', models.CharField(max_length=350, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
                ('running', models.BooleanField(default=True)),
                ('shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='neodashdb.Assets')),
            ],
            options={
                'db_table': '"scans"',
            },
        ),
        migrations.CreateModel(
            name='Vulns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('OWASP', models.IntegerField(default=5)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=350)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neodashdb.Assets')),
            ],
            options={
                'db_table': '"vulns"',
            },
        ),
    ]
